{
 "title": "moleculer-users-crud-app",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "15s,1m,2m,3m,5m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[NGINX] Current RPS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"api-gateway\"}[${interval}]))"
      }
     ]
    },
    {
     "title": "[MOL] Current RPS",
     "type": "stat",
     "description": "Среднее количество запросов в секунду за последние N секунд, где N - указанный интервал",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_total{type=\"remote\"}[${interval}]))"
      }
     ]
    },
    {
     "title": "[MOL] RPS",
     "type": "timeseries",
     "description": "Количество запросов в секунду",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_total{type=\"remote\"}[${interval}]))"
      }
     ]
    },
    {
     "title": "[MOL] RPS grouped by actions",
     "type": "timeseries",
     "description": "Количество запросов в секунду с группировкой по action'ам (endpoint'ам)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(action)(rate(moleculer_request_total{type=\"remote\"}[${interval}]))",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "[NGINX] Error rate (%)",
     "type": "timeseries",
     "description": "Процент 500'х ошибок относительно общего количества запросов",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"api-gateway\",status=~\"5.*\"}[${interval}])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\"api-gateway\"}[${interval}])) by (ingress) * 100",
       "legendFormat": "moleculer error rate"
      }
     ]
    },
    {
     "title": "[NGINX] Current error rate (%)",
     "type": "stat",
     "description": "Средний процент 500'х ошибок относительно общего количества запросов за последние N секунд, где N - указанный интервал",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"api-gateway\",status=~\"5.*\"}[${interval}])) by (ingress) / sum(rate(nginx_ingress_controller_requests{ingress=~\"api-gateway\"}[${interval}])) by (ingress) * 100",
       "legendFormat": "moleculer error rate"
      }
     ]
    },
    {
     "title": "[MOL] Error rate (%)",
     "type": "timeseries",
     "description": "Процент 500'х ошибок относительно общего количества запросов",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_error_total{errorCode=\"500\",type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
       "legendFormat": "moleculer error rate"
      }
     ]
    },
    {
     "title": "[MOL] Current error rate (%)",
     "type": "stat",
     "description": "Средний процент 500'х ошибок относительно общего количества запросов за последние N секунд, где N - указанный интервал",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_error_total{errorCode=\"500\",type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
       "legendFormat": "moleculer error rate"
      }
     ]
    },
    {
     "title": "[MOL] Error rate grouped by actions (%)",
     "type": "timeseries",
     "description": "Процент 500'х ошибок относительно общего количества запросов, сгруппированных по action'ам (endpoint'ам)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (action) (rate(moleculer_request_error_total{errorCode=\"500\",type=\"remote\"}[${interval}])) / sum by (action) (rate(moleculer_request_total{type=\"remote\"}[${interval}])) * 100",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[MOL] Latency (ms)",
     "type": "timeseries",
     "description": "Среднее время выполнения запросов в миллисекундах",
     "gridPos": { "h": 5, "w": 17, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_time_sum{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_time_count{type=\"remote\"}[${interval}]))"
      }
     ]
    },
    {
     "title": "[MOL] Current latency (ms)",
     "type": "stat",
     "description": "Среднее время выполнения запросов в миллисекундах за последние N секунд, где N - указанный интервал",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(moleculer_request_time_sum{type=\"remote\"}[${interval}])) / sum(rate(moleculer_request_time_count{type=\"remote\"}[${interval}]))"
      }
     ]
    },
    {
     "title": "[MOL] Percentiles of latencies requests (manual)",
     "type": "timeseries",
     "description": "Процентили задержек запросов (посчитано вручную)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
       "legendFormat": "50%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
       "legendFormat": "95%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
       "legendFormat": "99%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(moleculer_request_time_bucket{type=\"remote\"}[${interval}])) by (le))",
       "legendFormat": "99.9%-tile latency of requests"
      }
     ]
    },
    {
     "title": "[NGINX] Percentiles of latencies requests (manual)",
     "type": "timeseries",
     "description": "Процентили задержек запросов (посчитано вручную)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"api-gateway\"}[${interval}])) by (le))",
       "legendFormat": "50%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"api-gateway\"}[${interval}])) by (le))",
       "legendFormat": "95%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"api-gateway\"}[${interval}])) by (le))",
       "legendFormat": "99%-tile latency of requests"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=~\"api-gateway\"}[${interval}])) by (le))",
       "legendFormat": "99.9%-tile latency of requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\", container!=\"\", image!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\", image!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\", image!=\"\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"temp\",container!=\"\"}) by (pod)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"temp\"}[15m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"temp\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"temp\"}) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"temp\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"temp\"}) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSLQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=\"postgres\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"postgres\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{datname=~\"postgres\"}[${interval}])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{datname=~\"postgres\"}[${interval}])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"postgres\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    }
   ]
  }
 ]
}